import OpenGL
OpenGL.ERROR_CHECKING = False
from OpenGL.GL import *

import re
from contextlib import contextmanager, ExitStack
from pathlib import Path
from typing import Optional, Set, Dict, Any, Union, Callable, Sequence
import numpy as np
from pyglm import glm


SHADERS_ROOT = 'insectvision/engine/shaders'


def write_pytinybvh_preamble(preamble: str):
    """
    Writes PyTinyBVH #defines to a shader include that GLSL can #include.
    """

    shaders_root = Path(SHADERS_ROOT)
    file_name = 'pytinybvhPreamble.glsl'

    try:
        shaders_root.mkdir(parents=True, exist_ok=True)
        path = shaders_root / file_name
        path.write_text('// Auto-generated by PyTinyBVH.get_SSBO_bundle()\n' + preamble)

    except Exception as e:
        print(f"[Warn] Could not write '{file_name}': ", e)


class ShaderCompiler:
    """
    Handles resolving includes, injecting defines, and compiling/linking OpenGL shaders.
    """

    _include_pattern = re.compile(r'#include\s+"(.*?)"')
    _version_pattern = re.compile(r'^\s*#version\s+.*$', re.MULTILINE)

    def __init__(self, defines: Optional[Union[Set[str], Dict[str, Any]]] = None):

        self._shaders_root = Path(SHADERS_ROOT)

        self.defines = defines or {}
        self._include_stack = set()

    def resolve_shader_path(self, file_name: Union[str, Path], current_file: Optional[Union[str, Path]] = None) -> Path:
        """
        Locate a shader file in the shaders root.
        """

        shader_path = Path(file_name)

        # Try exact path
        if shader_path.exists():
            return shader_path

        cwd = self._shaders_root
        if current_file:
            current_file = Path(current_file)
            if current_file.is_file():
                cwd = current_file.parent
            elif current_file.is_dir():
                cwd = current_file

        # Try relative to cwd
        path = cwd / shader_path
        if path.exists():
            return path

        # Recursive search
        for candidate in self._shaders_root.rglob(shader_path.name):
            if candidate.is_file() and candidate.as_posix().endswith(shader_path.as_posix()):
                return candidate

        raise FileNotFoundError(f"Cannot find shader file '{file_name}'")

    def _process_includes(self, path: Path) -> str:
        """
        Recursively resolves #include directives while tracking the stack to prevent cycles.
        """

        if path in self._include_stack:
            raise RuntimeError(f"Circular #include detected: {path} is already in the include stack.")

        if not path.exists():
            raise FileNotFoundError(f"Cannot find shader file: {path}")

        self._include_stack.add(path)
        code = ""

        with path.open('r') as f:
            for line in f:
                match = self._include_pattern.match(line.strip())
                if match:
                    include_str = match.group(1)
                    include_path = self.resolve_shader_path(include_str, current_file=path)
                    code += self._process_includes(include_path) + "\n"
                else:
                    code += line

        self._include_stack.remove(path)
        return code

    def compile_shader(self, path: Union[str, Path], shader_type) -> int:
        """
        Reads, processes, and compiles a single shader stage from disk.
        """

        shader_path = self.resolve_shader_path(path)

        # clean state per compilation
        self._include_stack.clear()
        combined_code = self._process_includes(shader_path)

        matches = self._version_pattern.findall(combined_code)

        if not matches:
            raise RuntimeError(f"Shader '{shader_path}' and its includes contain no #version directive.")

        if len(matches) > 1:
            conflicts = "\n".join(f"  - {match.strip()}" for match in matches)
            raise RuntimeError(
                f"Shader '{shader_path}' contains multiple conflicting #version directives:\n{conflicts}")

        # Remove #version directive from its original position
        version_directive = matches[0]
        code_without_version = self._version_pattern.sub('', combined_code)

        # Inject #define blocks immediately after #version
        define_block = ''
        if self.defines:
            if isinstance(self.defines, dict):
                define_block = '\n'.join(f'#define {k} {v}' for k, v in sorted(self.defines.items())) + '\n'
            else:
                define_block = '\n'.join(f'#define {d}' for d in sorted(self.defines)) + '\n'

        final_code = version_directive + '\n' + define_block + code_without_version

        shader = glCreateShader(shader_type)
        glShaderSource(shader, final_code)
        glCompileShader(shader)

        if not glGetShaderiv(shader, GL_COMPILE_STATUS):
            error = glGetShaderInfoLog(shader).decode()
            glDeleteShader(shader)
            raise RuntimeError(f"Shader compilation error in {path}:\n{error}")

        return shader

    def load_program(self, path_vert=None, path_frag=None, path_geom=None, path_comp=None) -> int:
        """
        Compiles and links a shader program (rendering or compute).
        """

        shaders_to_link =[]

        try:
            if path_comp:
                shaders_to_link.append(self.compile_shader(path_comp, GL_COMPUTE_SHADER))
            else:
                if path_vert: shaders_to_link.append(self.compile_shader(path_vert, GL_VERTEX_SHADER))
                if path_frag: shaders_to_link.append(self.compile_shader(path_frag, GL_FRAGMENT_SHADER))
                if path_geom: shaders_to_link.append(self.compile_shader(path_geom, GL_GEOMETRY_SHADER))

            program = glCreateProgram()
            for shader in shaders_to_link:
                glAttachShader(program, shader)

            glLinkProgram(program)

            # Verification
            success = glGetProgramiv(program, GL_LINK_STATUS)
            error_log = ""
            if not success:
                error_log = glGetProgramInfoLog(program).decode()

            # detach and cleanup individual shader objects whether linking failed or not
            for shader in shaders_to_link:
                glDetachShader(program, shader)
                glDeleteShader(shader)

            if not success:
                glDeleteProgram(program)
                raise RuntimeError(f"Shader linking error:\n{error_log}")

            return program

        except Exception as e:
            # If compile fails halfway through, free previously compiled shaders in this pass
            for shader in shaders_to_link:
                glDeleteShader(shader)
            raise e


class ShaderProgram:
    """
    A wrapper for a GLSL shader program with cached uniform locations.
    """

    def __init__(self,
            vert_path=None,
            frag_path=None,
            geom_path=None,
            comp_path=None,
            defines: Optional[Union[Set[str], Dict[str, Any]]] = None,
        ):

        compiler = ShaderCompiler(defines=defines)

        self.program_id = compiler.load_program(
            path_vert=vert_path,
            path_frag=frag_path,
            path_geom=geom_path,
            path_comp=comp_path
        )

        self.locations = {}
        self.types = {}

        self.use()
        self._cache_uniforms()
        self.stop()

    def _cache_uniforms(self):
        """
        Query and cache all active uniform locations and their strict GL types.
        """
        num_uniforms = glGetProgramiv(self.program_id, GL_ACTIVE_UNIFORMS)

        for i in range(num_uniforms):
            name, size, type_ = glGetActiveUniform(self.program_id, i)

            if isinstance(name, np.ndarray):
                name = name.tobytes().decode('utf-8').rstrip('\x00')
            else:
                name = name.decode('utf-8')

            if name.endswith('[0]'):
                name = name[:-3]

            self.locations[name] = glGetUniformLocation(self.program_id, name)
            self.types[name] = type_

    def __enter__(self):
        self.use()
        return self

    def __exit__(self, exc_type, exc_val, exc_tb):
        self.stop()

    def use(self):
        """
        Bind the shader program.
        """
        glUseProgram(self.program_id)

    def stop(self):
        """
        Unbind the shader program.
        """
        glUseProgram(0)

    def get_loc(self, name):
        """
        Get cached uniform location.
        """
        return self.locations.get(name, -1)

    def free(self):
        """
        Delete the shader program.
        """
        glDeleteProgram(self.program_id)

##

class GPUResourceManager:
    """
    Manages global bindings and texture units to prevent overlapping when combining registries.
    """
    def __init__(self):
        self.ssbo_binding = 0
        self.texture_unit = 0

    def next_ssbo(self) -> int:
        val = self.ssbo_binding
        self.ssbo_binding += 1
        return val

    def next_texture(self) -> int:
        val = self.texture_unit
        self.texture_unit += 1
        return val


class BufferObject:
    """
    A wrapper around a GPU Buffer (SSBO, PBO, etc).
    """

    BUFFER_TYPES = {
        GL_SHADER_STORAGE_BUFFER: 'SSBO',
        GL_PIXEL_PACK_BUFFER: 'PBO',
        GL_ARRAY_BUFFER: 'VBO',
        GL_ELEMENT_ARRAY_BUFFER: 'EBO'
    }

    def __init__(
            self,
            name: str,
            handle: int,
            dtype: np.dtype,
            count: int,
            target: int = GL_SHADER_STORAGE_BUFFER,
            usage: int = GL_STATIC_DRAW,
            binding: Optional[int] = None,
            supports_async: bool = False,
            _async_reader: Optional['Callable'] = None,
    ):

        self.name = name
        self.handle = handle
        self.dtype = np.dtype(dtype)
        self.count = count
        self.target = target
        self.usage = usage
        self.binding = binding
        self._supports_async = supports_async
        self._async_reader = _async_reader

    def __repr__(self):
        sync_str = ' (async)' if self._supports_async else ''
        binding_str = f' binding={self.binding}' if self.binding else ''
        return (
            f"<{self.BUFFER_TYPES.get(self.target, 'Unknown buffer')}{sync_str} "
            f'name={self.name!r} handle={self.handle} '
            f'count={self.count} dtype={self.dtype}'
            f'{binding_str}>'
        )

    @contextmanager
    def bind(self, mode_override: Optional[int] = None):
        target = mode_override if mode_override is not None else self.target

        if self.binding is not None and mode_override is None:
            glBindBufferBase(target, self.binding, self.handle)
        else:
            glBindBuffer(target, self.handle)

        try:
            yield self
        finally:
            if self.binding is not None and mode_override is None:
                glBindBufferBase(target, self.binding, 0)
            else:
                glBindBuffer(target, 0)

    @property
    def itemsize(self) -> int:
        return int(self.dtype.itemsize)

    @property
    def nbytes(self) -> int:
        return self.count * self.itemsize

    def read(self, start: int = 0, count: Optional[int] = None) -> np.ndarray:
        """
        Synchronous read of [start:start+count] elements. Blocks until GPU has finished pending writes.
        """

        if count is None:
            count = self.count - start

        if start < 0 or count < 0 or (start + count) > self.count:
            raise IndexError(f"read range [{start}:{start + count}] out of bounds for {self.name} (count={self.count})")

        with self.bind():
            data_bytes = glGetBufferSubData(self.target, start * self.itemsize, count * self.itemsize)
            ret = np.frombuffer(data_bytes, dtype=self.dtype).copy()

        return ret

    def read_async(self) -> np.ndarray:
        """
        Asynchronous read using the double-buffered PBO path. Only available
        for buffers registered with `supports_async=True`.
        Returns the previous frame's data (zeros on the first frame).
        """
        if not self._supports_async or self._async_reader is None:
            raise RuntimeError(f"Buffer '{self.name}' does not support async read. Use read() instead.")
        return self._async_reader()

    def write(self, data: np.ndarray, start: int = 0) -> None:
        """
        Upload data to the buffer starting at element index `start` (default 0).
        """

        arr = np.ascontiguousarray(data)
        # allow raw bytes of matching size, raise on mismatch
        if arr.dtype != self.dtype and arr.nbytes != len(arr) * self.itemsize:
            raise TypeError(f"write(): data dtype {arr.dtype} does not match buffer dtype {self.dtype}.")

        n = arr.size if arr.dtype == self.dtype else arr.nbytes // self.itemsize
        if start < 0 or (start + n) > self.count:
            raise IndexError(f"write range [{start}:{start + n}] out of bounds for {self.name} (count={self.count})")

        with self.bind():
            glBufferSubData(self.target, start * self.itemsize, arr.nbytes, arr.tobytes())

    def resize(self, count: int, data: Optional[np.ndarray] = None) -> None:
        """Resize GPU buffer, optionally initialising with new data."""

        self.count = count

        with self.bind():
            if data is not None:
                arr = np.ascontiguousarray(data)
                glBufferData(self.target, self.nbytes, arr.tobytes(), self.usage)
            else:
                glBufferData(self.target, self.nbytes, None, self.usage)

    def reset(self) -> None:
        """
        Zero-out the entire GPU buffer immediately.
        """

        with self.bind():
            try:
                # glClearBufferSubData is the fast path
                glClearBufferSubData(
                    GL_SHADER_STORAGE_BUFFER,
                    GL_R32F,  # internal format for the clear (arbitrary for zero)
                    0, self.nbytes,
                    GL_RED, GL_FLOAT,
                    None,  # passing None clears to zero
                )
            except Exception:
                # if that didn't work just upload zeroes
                zeros = np.zeros(self.count, dtype=self.dtype)
                glBufferSubData(self.target, 0, self.nbytes, zeros)

    def free(self):
        if self.handle:
            glDeleteBuffers(1, [self.handle])
            self.handle = 0


class BufferRegistry:

    def __init__(self, resource_manager: Optional[GPUResourceManager] = None):
        self._buffers: Dict[str, BufferObject] = {}
        self._rm = resource_manager

    def __getitem__(self, name: str) -> BufferObject:
        if name not in self._buffers:
            raise KeyError(f"No buffer named {name!r}. Available: {sorted(self._buffers)}")

        return self._buffers[name]

    def __contains__(self, name: str) -> bool:
        return name in self._buffers

    def __iter__(self):
        return iter(self._buffers)

    def __repr__(self):
        return f"<BufferRegistry {list(self._buffers)}>"

    def keys(self):
        return self._buffers.keys()

    def items(self):
        return self._buffers.items()

    def values(self):
        return self._buffers.values()

    @property
    def shader_defines(self) -> Dict[str, Any]:
        return {f"BINDING_{b.name.upper()}": b.binding for b in self._buffers.values() if b.binding is not None}

    def allocate(self,
                 name: str,
                 dtype: np.dtype,
                 count: int,
                 target: int = GL_SHADER_STORAGE_BUFFER,
                 data: Optional[np.ndarray] = None,
                 usage: int = GL_STATIC_DRAW,
                 supports_async: bool = False,
                 _async_reader: Optional[callable] = None,
                 ) -> BufferObject:
        """Create a new SSBO, allocate GPU memory, and register it."""

        itemsize = np.dtype(dtype).itemsize
        size_bytes = count * itemsize

        handle = glGenBuffers(1)
        glBindBuffer(target, handle)

        if data is not None:
            data_arr = np.ascontiguousarray(data)
            glBufferData(target, size_bytes, data_arr.tobytes(), usage)
        else:
            glBufferData(target, size_bytes, None, usage)

        glBindBuffer(target, 0)

        binding = None
        if target in (GL_SHADER_STORAGE_BUFFER, GL_UNIFORM_BUFFER) and self._rm:
            binding = self._rm.next_ssbo()

        buf = BufferObject(
            name=name,
            handle=handle,
            dtype=dtype,
            count=count,
            target=target,
            usage=usage,
            binding=binding,
            supports_async=supports_async,
            _async_reader=_async_reader
        )

        if buf.name in self._buffers:
            raise KeyError(f"Buffer {buf.name!r} already registered.")

        self._buffers[buf.name] = buf

        return buf

    @contextmanager
    def grouped_bind(self, names: Optional[Union[str, Sequence[str]]] = None):
        """
        Binds a group of buffers.
        """
        if names is None:
            names =  self._buffers.keys()
        elif isinstance(names, str):
            names = [names]

        with ExitStack() as stack:
            for name in names:
                if name in self._buffers:
                    stack.enter_context(self._buffers[name].bind())
            yield

    def free(self):
        for buf in self._buffers.values():
            buf.free()
        self._buffers.clear()


class TextureObject:
    """Wrapper for a GPU Texture, managed automatically."""
    def __init__(self, name: str, handle: int, target: int, unit: int):
        self.name = name
        self.handle = handle
        self.target = target
        self.unit = unit

    @contextmanager
    def bind(self):
        glActiveTexture(GL_TEXTURE0 + self.unit)
        glBindTexture(self.target, self.handle)
        try:
            yield self
        finally:
            glActiveTexture(GL_TEXTURE0 + self.unit)
            glBindTexture(self.target, 0)

    def free(self):
        if self.handle:
            glDeleteTextures(1, [self.handle])
            self.handle = 0


class TextureRegistry:
    def __init__(self, resource_manager: Optional[GPUResourceManager] = None):
        self._textures: Dict[str, TextureObject] = {}
        self._rm = resource_manager

    def __getitem__(self, name: str) -> TextureObject:
        return self._textures[name]

    def __contains__(self, name: str) -> bool:
        return name in self._textures

    @contextmanager
    def bind_all(self):
        with ExitStack() as stack:
            for tex in self._textures.values():
                stack.enter_context(tex.bind())
            yield

    def allocate_2d(self, name: str, width: int, height: int, image_data=None, repeat=False, dtype=float) -> TextureObject:
        tex_id = glGenTextures(1)
        glBindTexture(GL_TEXTURE_2D, tex_id)

        glTexParameteri(GL_TEXTURE_2D, GL_TEXTURE_WRAP_S, GL_REPEAT if repeat else GL_CLAMP_TO_EDGE)
        glTexParameteri(GL_TEXTURE_2D, GL_TEXTURE_WRAP_T, GL_REPEAT if repeat else GL_CLAMP_TO_EDGE)
        glTexParameteri(GL_TEXTURE_2D, GL_TEXTURE_MIN_FILTER, GL_LINEAR)
        glTexParameteri(GL_TEXTURE_2D, GL_TEXTURE_MAG_FILTER, GL_LINEAR)

        if dtype == float:
            bitdepth, typ = GL_RGBA32F, GL_FLOAT
        else:
            bitdepth, typ = GL_SRGB_ALPHA, GL_UNSIGNED_BYTE

        glTexImage2D(GL_TEXTURE_2D, 0, bitdepth, width, height, 0, GL_RGBA, typ, image_data)
        glBindTexture(GL_TEXTURE_2D, 0)

        unit = self._rm.next_texture() if self._rm else 0
        tex = TextureObject(name, tex_id, GL_TEXTURE_2D, unit)
        self._textures[name] = tex
        return tex

    def allocate_array(self, name: str, texture_ids: Sequence[int]) -> TextureObject:
        if not texture_ids:
            raise ValueError("No texture IDs provided for array.")

        glBindTexture(GL_TEXTURE_2D, texture_ids[0])
        tex_w = glGetTexLevelParameteriv(GL_TEXTURE_2D, 0, GL_TEXTURE_WIDTH)
        tex_h = glGetTexLevelParameteriv(GL_TEXTURE_2D, 0, GL_TEXTURE_HEIGHT)
        glBindTexture(GL_TEXTURE_2D, 0)

        layer_count = len(texture_ids)
        tex_array_id = glGenTextures(1)

        glBindTexture(GL_TEXTURE_2D_ARRAY, tex_array_id)
        glTexStorage3D(GL_TEXTURE_2D_ARRAY, 1, GL_SRGB8_ALPHA8, tex_w, tex_h, layer_count)

        for i, tex_id in enumerate(texture_ids):
            glCopyImageSubData(
                tex_id, GL_TEXTURE_2D, 0, 0, 0, 0,
                tex_array_id, GL_TEXTURE_2D_ARRAY, 0, 0, 0, i,
                tex_w, tex_h, 1
            )

        glTexParameteri(GL_TEXTURE_2D_ARRAY, GL_TEXTURE_WRAP_S, GL_CLAMP_TO_EDGE)
        glTexParameteri(GL_TEXTURE_2D_ARRAY, GL_TEXTURE_WRAP_T, GL_CLAMP_TO_EDGE)
        glTexParameteri(GL_TEXTURE_2D_ARRAY, GL_TEXTURE_MIN_FILTER, GL_LINEAR)
        glTexParameteri(GL_TEXTURE_2D_ARRAY, GL_TEXTURE_MAG_FILTER, GL_LINEAR)
        glBindTexture(GL_TEXTURE_2D_ARRAY, 0)

        unit = self._rm.next_texture() if self._rm else 0
        tex = TextureObject(name, tex_array_id, GL_TEXTURE_2D_ARRAY, unit)
        self._textures[name] = tex
        return tex

    def register_existing(self, name: str, handle: int, target: int) -> TextureObject:
        unit = self._rm.next_texture() if self._rm else 0
        tex = TextureObject(name, handle, target, unit)
        self._textures[name] = tex
        return tex

    def free(self):
        for tex in self._textures.values():
            tex.free()
        self._textures.clear()


class UniformRegistry:
    """
    A dictionary-like registry that stores uniform values and automatically
    deduces the correct glUniform* call when applied to a shader.
    """

    def __init__(self, **kwargs):
        self._uniforms = {}
        self.update(**kwargs)

    def __setitem__(self, name: str, value):
        self._uniforms[name] = value

    def __getitem__(self, name: str):
        return self._uniforms[name]

    def __repr__(self):
        return f'<UniformRegistry({len(self._uniforms.keys())} uniforms)>'

    def update(self, **kwargs):
        """Update multiple uniforms at once."""
        self._uniforms.update(kwargs)

    def apply(self, shader: 'ShaderProgram'):
        """
        Applies all stored uniforms to the given shader.
        Safely ignores uniforms that the shader doesn't actively use.
        """
        for name, value in self._uniforms.items():
            loc = shader.get_loc(name)
            if loc == -1:
                continue  # Shader optimised this out or doesn't use it

            uniform_type = shader.types.get(name)

            # Bools and integers
            if isinstance(value, (int, bool, np.integer)):
                if uniform_type == GL_UNSIGNED_INT:
                    glUniform1ui(loc, int(value))
                else:
                    glUniform1i(loc, int(value))

            # Floats
            elif isinstance(value, (float, np.floating)):
                glUniform1f(loc, float(value))

            # PyGLM vectors and mats
            elif isinstance(value, (glm.vec2, glm.vec3, glm.vec4)):
                if len(value) == 2: glUniform2f(loc, value.x, value.y)
                elif len(value) == 3: glUniform3f(loc, value.x, value.y, value.z)
                elif len(value) == 4: glUniform4f(loc, value.x, value.y, value.z, value.w)


            elif isinstance(value, (glm.mat3, glm.mat4)):
                ptr = glm.value_ptr(value)
                if len(value) == 3: glUniformMatrix3fv(loc, 1, GL_FALSE, ptr)
                elif len(value) == 4: glUniformMatrix4fv(loc, 1, GL_FALSE, ptr)

            # Tuples / Lists (assumed floats)
            elif isinstance(value, (tuple, list)):
                if len(value) == 2: glUniform2f(loc, *value)
                elif len(value) == 3: glUniform3f(loc, *value)
                elif len(value) == 4: glUniform4f(loc, *value)

            # Numpy arrays
            elif isinstance(value, np.ndarray):
                val_flat = np.ascontiguousarray(value.flatten())
                if value.shape == (3, 3): glUniformMatrix3fv(loc, 1, GL_TRUE, val_flat)  # True for row-major numpy
                elif value.shape == (4, 4): glUniformMatrix4fv(loc, 1, GL_TRUE, val_flat)
                elif value.size == 2: glUniform2fv(loc, 1, val_flat)
                elif value.size == 3: glUniform3fv(loc, 1, val_flat)
                elif value.size == 4: glUniform4fv(loc, 1, val_flat)

            else:
                raise TypeError(f"UniformRegistry doesn't know how to dispatch type: {type(value)} for '{name}'")