import OpenGL
OpenGL.ERROR_CHECKING = False
from OpenGL.GL import *

import re
from pathlib import Path
from typing import Optional, Set, Dict, Any, Union
import numpy as np


SHADERS_ROOT = 'insectvision/engine/shaders'


def write_pytinybvh_preamble(preamble: str):
    """
    Writes PyTinyBVH #defines to a shader include that GLSL can #include.
    """

    shaders_root = Path(SHADERS_ROOT)
    file_name = 'pytinybvhPreamble.glsl'

    try:
        shaders_root.mkdir(parents=True, exist_ok=True)
        path = shaders_root / file_name
        path.write_text('// Auto-generated by PyTinyBVH.get_SSBO_bundle()\n' + preamble)

    except Exception as e:
        print(f"[Warn] Could not write '{file_name}': ", e)


class ShaderCompiler:
    """
    Handles resolving includes, injecting defines, and compiling/linking OpenGL shaders.
    """

    _include_pattern = re.compile(r'#include\s+"(.*?)"')
    _version_pattern = re.compile(r'^\s*#version\s+.*$', re.MULTILINE)

    def __init__(self, defines: Optional[Union[Set[str], Dict[str, Any]]] = None):

        self._shaders_root = Path(SHADERS_ROOT)

        self.defines = defines or {}
        self._include_stack = set()

    def resolve_shader_path(self, file_name: Union[str, Path], current_file: Optional[Union[str, Path]] = None) -> Path:
        """
        Locate a shader file in the shaders root.
        """

        shader_path = Path(file_name)

        # Try exact path
        if shader_path.exists():
            return shader_path

        cwd = self._shaders_root
        if current_file:
            current_file = Path(current_file)
            if current_file.is_file():
                cwd = current_file.parent
            elif current_file.is_dir():
                cwd = current_file

        # Try relative to cwd
        path = cwd / shader_path
        if path.exists():
            return path

        # Recursive search
        for candidate in self._shaders_root.rglob(shader_path.name):
            if candidate.is_file() and candidate.as_posix().endswith(shader_path.as_posix()):
                return candidate

        raise FileNotFoundError(f"Cannot find shader file '{file_name}'")

    def _process_includes(self, path: Path) -> str:
        """
        Recursively resolves #include directives while tracking the stack to prevent cycles.
        """

        if path in self._include_stack:
            raise RuntimeError(f"Circular #include detected: {path} is already in the include stack.")

        if not path.exists():
            raise FileNotFoundError(f"Cannot find shader file: {path}")

        self._include_stack.add(path)
        code = ""

        with path.open('r') as f:
            for line in f:
                match = self._include_pattern.match(line.strip())
                if match:
                    include_str = match.group(1)
                    include_path = self.resolve_shader_path(include_str, current_file=path)
                    code += self._process_includes(include_path) + "\n"
                else:
                    code += line

        self._include_stack.remove(path)
        return code

    def compile_shader(self, path: Union[str, Path], shader_type) -> int:
        """
        Reads, processes, and compiles a single shader stage from disk.
        """

        shader_path = self.resolve_shader_path(path)

        # clean state per compilation
        self._include_stack.clear()
        combined_code = self._process_includes(shader_path)

        matches = self._version_pattern.findall(combined_code)

        if not matches:
            raise RuntimeError(f"Shader '{shader_path}' and its includes contain no #version directive.")

        if len(matches) > 1:
            conflicts = "\n".join(f"  - {match.strip()}" for match in matches)
            raise RuntimeError(
                f"Shader '{shader_path}' contains multiple conflicting #version directives:\n{conflicts}")

        # Remove #version directive from its original position
        version_directive = matches[0]
        code_without_version = self._version_pattern.sub('', combined_code)

        # Inject #define blocks immediately after #version
        define_block = ''
        if self.defines:
            if isinstance(self.defines, dict):
                define_block = '\n'.join(f'#define {k} {v}' for k, v in sorted(self.defines.items())) + '\n'
            else:
                define_block = '\n'.join(f'#define {d}' for d in sorted(self.defines)) + '\n'

        final_code = version_directive + '\n' + define_block + code_without_version

        shader = glCreateShader(shader_type)
        glShaderSource(shader, final_code)
        glCompileShader(shader)

        if not glGetShaderiv(shader, GL_COMPILE_STATUS):
            error = glGetShaderInfoLog(shader).decode()
            glDeleteShader(shader)
            raise RuntimeError(f"Shader compilation error in {path}:\n{error}")

        return shader

    def load_program(self, path_vert=None, path_frag=None, path_geom=None, path_comp=None) -> int:
        """
        Compiles and links a shader program (rendering or compute).
        """

        shaders_to_link =[]

        try:
            if path_comp:
                shaders_to_link.append(self.compile_shader(path_comp, GL_COMPUTE_SHADER))
            else:
                if path_vert: shaders_to_link.append(self.compile_shader(path_vert, GL_VERTEX_SHADER))
                if path_frag: shaders_to_link.append(self.compile_shader(path_frag, GL_FRAGMENT_SHADER))
                if path_geom: shaders_to_link.append(self.compile_shader(path_geom, GL_GEOMETRY_SHADER))

            program = glCreateProgram()
            for shader in shaders_to_link:
                glAttachShader(program, shader)

            glLinkProgram(program)

            # Verification
            success = glGetProgramiv(program, GL_LINK_STATUS)
            error_log = ""
            if not success:
                error_log = glGetProgramInfoLog(program).decode()

            # detach and cleanup individual shader objects whether linking failed or not
            for shader in shaders_to_link:
                glDetachShader(program, shader)
                glDeleteShader(shader)

            if not success:
                glDeleteProgram(program)
                raise RuntimeError(f"Shader linking error:\n{error_log}")

            return program

        except Exception as e:
            # If compile fails halfway through, free previously compiled shaders in this pass
            for shader in shaders_to_link:
                glDeleteShader(shader)
            raise e


class ShaderProgram:
    """
    A wrapper for a GLSL shader program with cached uniform locations.
    """

    def __init__(self,
            vert_path=None,
            frag_path=None,
            geom_path=None,
            comp_path=None,
            defines: Optional[Union[Set[str], Dict[str, Any]]] = None,
        ):

        compiler = ShaderCompiler(defines=defines)

        self.program_id = compiler.load_program(
            path_vert=vert_path,
            path_frag=frag_path,
            path_geom=geom_path,
            path_comp=comp_path
        )

        self.locations = {}

        self.use()
        self._cache_uniforms()
        self.stop()

    def _cache_uniforms(self):
        """
        Query and cache all active uniform locations.
        """
        num_uniforms = glGetProgramiv(self.program_id, GL_ACTIVE_UNIFORMS)

        for i in range(num_uniforms):
            name, size, type_ = glGetActiveUniform(self.program_id, i)

            if isinstance(name, np.ndarray):
                name = name.tobytes().decode('utf-8').rstrip('\x00')
            else:
                name = name.decode('utf-8')

            if name.endswith('[0]'):
                name = name[:-3]

            self.locations[name] = glGetUniformLocation(self.program_id, name)

    def __enter__(self):
        self.use()
        return self

    def __exit__(self, exc_type, exc_val, exc_tb):
        self.stop()

    def use(self):
        """
        Bind the shader program.
        """
        glUseProgram(self.program_id)

    def stop(self):
        """
        Unbind the shader program.
        """
        glUseProgram(0)

    def get_loc(self, name):
        """
        Get cached uniform location.
        """
        return self.locations.get(name, -1)

    def free(self):
        """
        Delete the shader program.
        """
        glDeleteProgram(self.program_id)