[project]
name = "RhabdoForge"
version = "0.9.5"
description = "A modular, hardware-agnostic GPU rendering engine for closed-loop insect vision, sub-ommatidial active sensing, and neuromorphic modelling."
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "glfw>=2.9.0",
    "matplotlib>=3.10.3",
    "moderngl>=5.12.0",
    "numpy==2.2",
    "pillow>=11.3.0",
    "pyopengl>=3.1.9",
    "scipy>=1.16.0",
    "trimesh[easy]",
    "pyvista",
    "pyglm",
    "pytinybvh @ git+https://github.com/FlorentLM/pytinybvh.git#egg=pytinybvh",
    "dearpygui>=2.3.1",
    "opencv-python>=4.13.0.92",
    "joblib>=1.5.3",
]
