#version 430 core

#ifdef PATH_TRACING
#include "tracePath.glsl"
#else
#include "traceSimple.glsl"
#endif

layout (local_size_x = 64, local_size_y = 1, local_size_z = 1) in;

layout(std430, binding = BINDING_RCPT_STATIC) readonly buffer RcptStaticBlock { ReceptorStatic    rcpt_static[];  };
layout(std430, binding = BINDING_RCPT_DYNAMIC) readonly buffer RcptDynamicBlock { ReceptorDynamic rcpt_dynamic[]; };
layout(std430, binding = BINDING_LENS_STATIC) readonly buffer LensStaticBlock { LensStatic        lens_static[];  };
layout(std430, binding = BINDING_RAYS_INTERMEDIATE) writeonly buffer RayResultBuffer { vec4       ray_results[];  };

// Uniforms
uniform uint dither_counter;
uniform mat4 cam_to_world;
uniform int nb_samples;
uniform int randomness_mode;
uniform bool use_hybrid_sampling;
uniform int  sampling_mode;

void main() {
    uint global_id = gl_GlobalInvocationID.x;
    uint total_receptors = rcpt_static.length();

    if (global_id >= (nb_samples * total_receptors)) return;    // stop if out of bounds

    uint rcpt_idx = global_id / nb_samples;
    uint sample_idx = global_id % nb_samples;

    ReceptorStatic rs = rcpt_static[rcpt_idx];
    ReceptorDynamic rd = rcpt_dynamic[rcpt_idx];

    // Lens data for this receptor
    uint lens_idx = unpack_lens_id(rs.metadata);
    LensStatic ls = lens_static[lens_idx];

    uint base_seed = rcpt_idx * 1973u + dither_counter * 26699u;
    uint rng_state = pcg_hash(base_seed + sample_idx * 749u);

    // Generate ray direction
    vec3 F = normalize((cam_to_world * vec4(rd.direction, 0.0)).xyz);
    vec3 P = (cam_to_world * vec4(rs.position, 1.0)).xyz;
    vec3 up = abs(F.y) > 0.99 ? vec3(1,0,0) : vec3(0,1,0);

    // tangent and bitangent
    vec3 T = normalize(cross(up, F));
    vec3 B = cross(F, T);

    Sampler s = get_samples(randomness_mode, sample_idx, uint(nb_samples), rcpt_idx, uint(dither_counter));

    float ray_weight;
    vec3 direction;
    if (use_hybrid_sampling) {
        direction = sampledir_hybrid(sampling_mode, rs, rd, ls, T, B, F, s.u1, s.u2, ray_weight);
    } else {
        direction = sampledir_importance(rs, rd, T, B, F, s.u1, s.u2, ray_weight);
    }

    Ray ray;
    ray.origin = P;
    ray.t = 1.0/0.0;
    ray.inv_direction = 1.0 / direction;

    vec3 final_color = trace(ray, rng_state);

    // Alpha channel stores ray weight for reduction.comp
    ray_results[global_id] = vec4(final_color, ray_weight);
}
