#version 430 core

#ifdef PATH_TRACING
#include "tracePath.glsl"
#else
#include "traceSimple.glsl"
#endif

layout (local_size_x = 64, local_size_y = 1, local_size_z = 1) in;

layout(std430, binding = BINDING_RCPT_STATIC) readonly buffer RcptStaticBlock  { ReceptorStatic  rcpt_static[]; };
layout(std430, binding = BINDING_RCPT_DYNAMIC) readonly buffer RcptDynamicBlock { ReceptorDynamic rcpt_dynamic[]; };
layout(std430, binding = BINDING_RAYS_INTERMEDIATE) writeonly buffer RayResultBuffer { vec4 ray_results[]; };

// Uniforms
uniform uint dither_counter;
uniform mat4 cam_to_world;
uniform int nb_samples;
uniform bool use_quasi_random;

void main() {
    uint global_id = gl_GlobalInvocationID.x;
    uint total_receptors = rcpt_static.length();

    // Stop if out of bounds
    if (global_id >= (nb_samples * total_receptors)) {
        return;
    }

    uint rcpt_idx = global_id / nb_samples;
    uint sample_idx = global_id % nb_samples;

    ReceptorStatic rs = rcpt_static[rcpt_idx];
    ReceptorDynamic rd = rcpt_dynamic[rcpt_idx];

    uint base_seed = rcpt_idx * 1973u + dither_counter * 26699u;
    uint rng_state = pcg_hash(base_seed + sample_idx * 749u);

    // Generate ray direction
    vec3 F = normalize((cam_to_world * vec4(rd.direction, 0.0)).xyz);
    vec3 P = (cam_to_world * vec4(rs.position, 1.0)).xyz;
    vec3 up = abs(F.y) > 0.99 ? vec3(1,0,0) : vec3(0,1,0);

    // tangent and bitangent
    vec3 T = normalize(cross(up, F));
    vec3 B = cross(F, T);

    float r1, r2;
    if (use_quasi_random) {
        // Halton sequence
        uint halton_idx = dither_counter * uint(nb_samples) + sample_idx  + 1u;
        uint hash = pcg_hash(rcpt_idx * 1973u);

        r1 = clamp(fract(halton_sequence(halton_idx, 2u) + float(hash & 0xFFFFu)/65535.0), 1e-6, 1.0);
        r2 = fract(halton_sequence(halton_idx, 3u) + float((hash >> 16u) & 0xFFFFu)/65535.0);

    } else {
        // Regular randomness
        r1 = random_float(rng_state);
        r2 = random_float(rng_state);
    }
    vec3 direction = sampledir(rs, rd, T, B, F, r1, r2);

    Ray ray;
    ray.origin = P;
    ray.t = 1.0/0.0;
    ray.inv_direction = 1.0 / direction;

    vec3 final_color = trace(ray, rng_state);
    ray_results[global_id] = vec4(final_color, 1.0);
}
