#version 430 core

#include "raytracing_commons.glsl"

layout (local_size_x = 256, local_size_y = 1, local_size_z = 1) in;

// Input and output
layout(std430, binding = 0) readonly buffer OmmatidiaInputBuffer { Ommatidium u_ommatidia_data[]; };
layout(std430, binding = 4) writeonly buffer RayResultBuffer { vec4 u_ray_results[]; };

// Uniforms
uniform float u_time;
uniform mat4 u_camera_to_world;
uniform int u_samples_per_ommatidium;


void main() {
    uint global_id = gl_GlobalInvocationID.x;

    if (global_id >= (u_samples_per_ommatidium * u_ommatidia_data.length())) {
        return;
    }

    uint ommatidium_idx = global_id / u_samples_per_ommatidium;
    uint sample_idx = global_id % u_samples_per_ommatidium;

    Ommatidium om = u_ommatidia_data[ommatidium_idx];

    // Generate ray
    vec3 om_world_dir = (u_camera_to_world * om.direction).xyz;
    vec3 om_world_origin = (u_camera_to_world * om.origin).xyz;
    vec3 up = abs(om_world_dir.y) > 0.99 ? vec3(1.0, 0.0, 0.0) : vec3(0.0, 1.0, 0.0);
    vec3 tangent = normalize(cross(up, om_world_dir));
    vec3 bitangent = cross(om_world_dir, tangent);
    float r1 = rand(vec2(ommatidium_idx, sample_idx), u_time);
    float r2 = rand(vec2(ommatidium_idx, sample_idx) + 0.5, u_time);
    vec3 direction = sampledir(om, tangent, bitangent, om_world_dir, r1, r2);

    // Setup Ray
    Ray r;
    r.origin = om_world_origin;
    r.t = 1.0/0.0;
    r.inv_direction = 1.0 / direction;

    // Trace and store result
    vec3 final_color = trace(r);
    u_ray_results[global_id] = vec4(final_color, 1.0);
}