#version 430 core

#include "raytracing_commons.glsl"

layout (local_size_x = 16, local_size_y = 16, local_size_z = 1) in;

// Output
layout(binding = 0, rgba32f) uniform writeonly image2D u_output_image;

// Uniforms
uniform mat4 u_camera_to_world;

void main() {
    ivec2 pixel_coords = ivec2(gl_GlobalInvocationID.xy);
    ivec2 dims = imageSize(u_output_image);

    if (pixel_coords.x >= dims.x || pixel_coords.y >= dims.y) {
        return;
    }

    // Generate Ray
    vec2 uv = (vec2(pixel_coords) + 0.5) / vec2(dims);
    uv.y = 1.0 - uv.y; // flip Y-axis

    float phi = uv.x * TWOPI + HPI;
    float theta = uv.y * PI;
    vec3 local_dir = vec3(sin(theta) * cos(phi), cos(theta), sin(theta) * sin(phi));

    // Setup Ray
    Ray r;
    r.origin = u_camera_to_world[3].xyz;
    vec3 direction = normalize((u_camera_to_world * vec4(local_dir, 0.0)).xyz);
    r.t = 1.0/0.0;
    r.inv_direction = 1.0 / direction;

    // Trace and store result
    vec3 final_color = trace(r);
    imageStore(u_output_image, pixel_coords, vec4(final_color, 1.0));
}