#version 430 core

#include "raytracing_commons.glsl"

layout (local_size_x = 16, local_size_y = 16, local_size_z = 1) in;

// Output
layout(binding = 0, rgba32f) uniform writeonly image2D output_image;

// Uniforms
uniform mat4 cam_to_world;     // view-space -> world-space
uniform mat4 inv_projection;   // clip-space -> view-space

void main() {
    ivec2 pixel_coords = ivec2(gl_GlobalInvocationID.xy);
    ivec2 dims = imageSize(output_image);

    // Guard for oversized dispatch
    if (pixel_coords.x >= dims.x || pixel_coords.y >= dims.y) return;

    // Pixel center -> Normalized Device Coordinates in [-1, 1]
    vec2 uv = (vec2(pixel_coords) + vec2(0.5)) / vec2(dims);
    vec2 ndc = uv * 2.0 - 1.0;

    vec4 p_near_view = inv_projection * vec4(ndc, -1.0, 1.0); p_near_view /= p_near_view.w;
    vec4 p_far_view = inv_projection * vec4(ndc, 1.0, 1.0); p_far_view  /= p_far_view.w;

    vec3 origin = (cam_to_world * vec4(0.0, 0.0, 0.0, 1.0)).xyz;
    vec3 p_far = (cam_to_world * vec4(p_far_view.xyz, 1.0)).xyz;
    vec3 direction = normalize(p_far - origin);

    Ray r;
    r.origin = origin;
    r.t = 1.0/0.0;
    r.inv_direction = 1.0 / direction;

    // Trace and write
    vec3 final_color = trace(r);
    imageStore(output_image, pixel_coords, vec4(final_color, 1.0));
}
