#version 430 core
#include "commons.glsl"

layout (local_size_x = 64, local_size_y = 1, local_size_z = 1) in;

layout(std430, binding = BINDING_RHAB_STATIC) readonly buffer RhabStaticBlock  { RhabdomereStatic  rhab_static[]; };
layout(std430, binding = BINDING_RHAB_DYNAMIC) readonly buffer RhabDynamicBlock { RhabdomereDynamic rhab_dynamic[]; };
layout(std430, binding = BINDING_OMM_STATIC) readonly buffer OmmatidiumStaticBlock  { OmmatidiumStatic      omm_static[]; };
layout(std430, binding = BINDING_RAYS_INTERMEDIATE) writeonly buffer RayResultBuffer { vec4 ray_results[]; };

layout(binding = 0) uniform samplerCube scene_cubemap;

uniform int nb_rhabdomeres;
uniform int nb_samples;
uniform float dither_counter;
uniform int randomness_mode;
uniform bool use_hybrid_sampling;
uniform int sampling_mode;

void main() {
    uint global_id = gl_GlobalInvocationID.x;
    uint total_count = rhab_static.length();

    if (global_id >= (nb_samples * total_count)) return;    // stop if out of bounds

    uint rhab_idx = global_id / nb_samples;
    uint sample_idx = global_id % nb_samples;

    RhabdomereStatic rs = rhab_static[rhab_idx];
    RhabdomereDynamic rd = rhab_dynamic[rhab_idx];

    // Ommatidium data for this rhabdomere
    uint omm_idx = unpack_omm_id(rs.metadata);
    OmmatidiumStatic os = omm_static[omm_idx];

    /// Reconstruct tangent frame
    vec3 F = rd.curr_direction;
    vec3 T = normalize(os.right - F * dot(os.right, F));
    vec3 B = normalize(cross(F, T));

    Sampler s = get_samples(randomness_mode, sample_idx, uint(nb_samples), rhab_idx, uint(dither_counter));

    float ray_weight;
    vec3 sample_dir;
    if (use_hybrid_sampling) {
        sample_dir = sampledir_hybrid(sampling_mode, rs, rd, os, T, B, F, s.u1, s.u2, ray_weight);
    } else {
        sample_dir = sampledir_importance(rs, rd, os, T, B, F, s.u1, s.u2, ray_weight);
    }

    vec3 color = texture(scene_cubemap, sample_dir).rgb;

    // Alpha channel stores ray weight for reduction.comp
    ray_results[global_id] = vec4(color, ray_weight);
}